Document: calimero
Title: Debian calimero Manual
Author: <insert document author here>
Abstract: This manual describes what calimero is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/calimero/calimero.sgml.gz

Format: postscript
Files: /usr/share/doc/calimero/calimero.ps.gz

Format: text
Files: /usr/share/doc/calimero/calimero.text.gz

Format: HTML
Index: /usr/share/doc/calimero/html/index.html
Files: /usr/share/doc/calimero/html/*.html
